### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by PoLaKoSz** [prajjwaldimri/Genius.NET#10]
Hi!

The DOCS link here:
> ## Usage
>
> Please read the [DOCS](http://prajjwaldimri.github.io/Genius.NET) for complete instructions.

and the project link is also broken.

**Comment by prajjwaldimri** [comment]
Alright. On it

**Comment by prajjwaldimri** [comment]
Fixed. It was happening because I moved the source code of my personal website to Gitlab and forgot to remove the CNAME association left on the Github repo.
