### ISSUE TITLE
Nuget Out of Date

### ISSUE THREAD

**Issue by scgough** [prajjwaldimri/Genius.NET#15]
@prajjwaldimri it looks like the version of this on nuget is out of date even though it’s labelled up as 2.0. For example the AppleMusicId in Models.Song doesn’t exist on the nuget version. 
Could you release the latest code to Nuget please?

**Comment by prajjwaldimri** [comment]
Sure. On it

**Comment by prajjwaldimri** [comment]
Done

**Comment by scgough** [comment]
Thank you @prajjwaldimri !

**Comment by scgough** [comment]
@prajjwaldimri  Ive updated to 3.0.0 (I've even removed and re-added the package) in my project but it is saying that `Genius.Models.Song` has no definition for `AppleMusicId` :/

**Comment by prajjwaldimri** [comment]
I will check. ~~Probably I will do a complete rewrite of this library to make it compatible with newer .Net projects.~~ Started working on a newer version on the library.

**Comment by prajjwaldimri** [comment]
@scgough A complete rewritten library is now up on Nuget. Version 4.0.0

**Comment by prajjwaldimri** [comment]
Check it out and tell me if there are any issues.

**Comment by scgough** [comment]
Thanks @prajjwaldimri thats great. I’ll upgrade the library and test it out in my project!

**Comment by prajjwaldimri** [comment]
Also, I accidentally uploaded it to https://www.nuget.org/packages/Genius/

So, now to install it on nuget you can just type Install-Package Genius (4 keystrokes saved)

Now it is available on Genius and Genius.NET on nuget

**Comment by scgough** [comment]
Just to update on this. I installed 4.0.0 (under Genius.NET as I say you had also updated that) and all is good. AppleMusicId is working nicely now! 
I'm going to explore the other features too. Thanks for the update @prajjwaldimri
