### ISSUE TITLE
Error on SongClient.GetSong(songId)

### ISSUE THREAD

**Issue by scgough** [prajjwaldimri/Genius.NET#16]
Hi!
The new update is working well but I seem to be getting exceptions on the following method:

`var response = await geniusClient.SongClient.GetSong(songId);`

This only seems to happen for some songs. One of which is `5524080`

I don't _think_ it's anything to do with API limits as it's consistent for some songs. It looks like an error parsing some user data from the info below...perhaps expecting a string value for the `avatar:tiny:url` when the API provides `null`?

**Exception:**

`Expected: ", null`

**Stack Trace:** 
```
  at Jil.JSON.Deserialize[T](TextReader reader, Options options)
   at Genius.Clients.SongClient.<GetSong>d__2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
``` 

**SnippetAfterError:**
`"api_path":"/users/93685","avatar":{"tiny":{"url":`

**Comment by prajjwaldimri** [comment]
So the snippet after error means that the error is happening before `api_path` field. 

That is the `lyrics_marked_complete_by` field. If you see in the library it is `string` type however in the API it is a `User` type.

**Comment by prajjwaldimri** [comment]
4.0.1 will be up in a few moments. It will fix this issue

**Comment by scgough** [comment]
Wow lightning fast!
