### ISSUE TITLE
Jil.DeserializationException: Expected digit when requesting not existing page with ArtistClient.GetArtistsSongs method

### ISSUE THREAD

**Issue by 93Omar** [prajjwaldimri/Genius.NET#18]
When I try to request an invalid page, using, for example, that piece of code:
```C#
GeniusClient _geniusClient;
var songs = await _geniusClient.ArtistClient.GetArtistsSongs(16775, sort: "title", perPage: "10", page: "3000");
```
I'm getting this error:
`Jil.DeserializationException: Expected digit`

**Comment by 93Omar** [comment]
I fixed the error by myself.
You have to make the `NextPage` property in `ArtistsSongsData` nullable:
```C#
[JilDirective(Name = "next_page")] public ulong? NextPage { get; set; }
```

I cannot open a pull request since I don't have the write permissions. If you can give me the permission I will open the PR adding also some unit tests.

**Comment by prajjwaldimri** [comment]
Hey @OmarPani93.I think you can open a PR without having write access to this repository. I will merge it when you are done.

**Comment by 93Omar** [comment]
Hi @prajjwaldimri, I tried to create a new branch from master but I can't push it. Do you want me to use another branch instead?

**Comment by prajjwaldimri** [comment]
You won't be able to push directly to the repo as is convention in open source projects. 
So, to contribute, you would need to first fork this repo and then push your changes to that fork and then create a pull request here.

**Comment by 93Omar** [comment]
Ok, thank you, I will try that. Sorry but this is actually my first time using GitHub contributing on some project.

**Comment by prajjwaldimri** [comment]
Hey, no worries :) You can see this link on how to create a PR: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request.

Feel free to comment here if you have any other queries.
