### ISSUE TITLE
Cant get an album

### ISSUE THREAD

**Issue by smile437** [prajjwaldimri/Genius.NET#7]
After `Search.DoSearch();` in album property always see null. How to get this information?

**Comment by prajjwaldimri** [comment]
Hi @smile437. Can you provide me more information about the bug you are facing and how to reproduce it? Thanks

**Comment by smile437** [comment]
`var hits = await Search.DoSearch();`
than go to `hits[n].Result.Album` and its always null

**Comment by prajjwaldimri** [comment]
@smile437 
First assign your auth token as 
`Search.AuthenticationToken = "<Authentication Token>`

Then add searchterm, e.g.
`Search.SearchTerm = "Sia"`

Then initiate the search:  `var hits = Search.DoSearch().Result`

Doing the above I get multiple hits. Reopen this issue if you still face problem.

![image](https://user-images.githubusercontent.com/9110203/30281402-ef47d6c4-972f-11e7-843f-a966acfad429.png)
